### ISSUE TITLE
The "Also In This Section" Link in Events Page is strange, can't figure out how to remove

### ISSUE THREAD

**Issue by LauraLewis15** [dennereed/blackinbioanth#4]

**Comment by dennereed** [comment]
The default templates include a sidebar with links to related pages. It appears even when empty or sparsely populated which is not idea. It can be removed by choosing a different template in the page content tab under the field TEMPLATE STRING. For example chooseing Grid Also In This Section instead of Default removed the sidebar from the Events page.
![Screen Shot 2021-03-04 at 12 56 34 PM](https://user-images.githubusercontent.com/6537616/110029539-7198de00-7ce9-11eb-96fd-3d6c43f2f964.png)

**Comment by LauraLewis15** [comment]
Ahhhh yes I did see this option, but I didn’t actually play with it to find out what it did. Thanks for explaining!!
